spring:
  application:
    name: server-a-demo

# 配置链路相关信息
  sleuth:
    sampler:
      #设置sleuth收集信息的比率为1,默认10%
      probability: 1
  zipkin:
    #zipkin服务端地址
    base-url: http://localhost:9411
    #discovery-client-enabled: true


server:
  port: 9001



## eureka 客户端基本配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
    healthcheck:
      enabled: true


